### ISSUE TITLE
Segfault in delete_with, seemingly resulting from a combination of entity relation and triggers.

### ISSUE THREAD

**Issue by nicokruger** [SanderMertens/flecs#725]
**Describe the bug**
Internal segfault during delete_with in certain circumstances.

**To Reproduce**

```
#include <iostream>
#include "flecs.h"

struct Position
{
  int x;
  int y;
};

struct PhysicsBody
{
  float size;
  float density;
};

struct OrbitAround
{
  float radius;
};

flecs::entity create_thing(flecs::world &ecs, int x, int y) {
  flecs::entity e = ecs.entity();
  e.set<Position>({
      .x = x,
      .y = y
  });
  e.set<PhysicsBody>({
      .size = 1,
      .density = 1
  });
  return e;
}

void delete_stuff(flecs::world &ecs) {
  // this should delete all objects we create with create_thing
  ecs.delete_with<PhysicsBody>();
}

int main()
{
  flecs::world ecs;
  ecs.trigger<PhysicsBody>()
    .event(flecs::OnSet)
    .each([](flecs::entity e, const PhysicsBody &body) {
        std::cout << "create pbody on " << e << std::endl;
      });


  auto p1 = create_thing(ecs, 0, 0);
  auto p2 = create_thing(ecs, 10, 10);

  p1.set<OrbitAround>(p2, {
      .radius = 10
  });

  ecs.progress();
  ecs.progress();
  ecs.progress();
  ecs.progress();
  ecs.progress();

  std::cout << "deleting..." << std::endl;
  delete_stuff(ecs);
  std::cout << "done" << std::endl;
}
```

Running the above code results in a segfault on flecs master:
```
Undefined command: ".".  Try "help".
(gdb) run
Starting program: /home/nico/flecs-bug/test

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.archlinux.org
Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
create pbody on 543
create pbody on 544
deleting...

Program received signal SIGSEGV, Segmentation fault.
0x000055555558c830 in delete_objects (world=0x55555565bf30, table=0x3a862d81c5e90f95) at /home/nico/flecs-bug/flecs.c:6906
w6906           ecs_entity_t *entities = ecs_vector_first(
(gdb) where
#0  0x000055555558c830 in delete_objects (world=0x55555565bf30, table=0x3a862d81c5e90f95) at /home/nico/flecs-bug/flecs.c:6906
#1  0x000055555558cd56 in on_delete_id_action (world=0x55555565bf30, id=37, action=307) at /home/nico/flecs-bug/flecs.c:7069
#2  0x000055555558ce8f in on_delete_action (world=0x55555565bf30, id=37, action=307) at /home/nico/flecs-bug/flecs.c:7104
#3  0x000055555558cfa7 in ecs_delete_with (world=0x55555565bf30, id=37) at /home/nico/flecs-bug/flecs.c:7136
#4  0x000055555555bd28 in flecs::world::delete_with (this=0x7fffffffdcf0, the_id=37) at /home/nico/flecs-bug/flecs.h:15539
#5  0x000055555555d9c4 in flecs::world::delete_with<PhysicsBody> (this=0x7fffffffdcf0) at /home/nico/flecs-bug/flecs.h:15550
#6  0x0000555555557753 in delete_stuff (ecs=...) at /home/nico/flecs-bug/test.cpp:36
#7  0x000055555555797d in main () at /home/nico/flecs-bug/test.cpp:63
(gdb)
```

**Expected behavior**
The delete_with<PhysicsBody> should delete all entities and then the program should exit.

**Additional context**
Interestingly, the problem seems to go away if you change the delete_with to delete_with < Position >  or remove the PhysicsBody trigger or the relation between the two components.

**Comment by SanderMertens** [comment]
Fixed!

**Comment by nicokruger** [comment]
Working as advertised! Thanks!
