### ISSUE TITLE
Adding component followed by clearing entity of components causes `INTERNAL_ERROR` assertion

### ISSUE THREAD

**Issue by Evangel63** [SanderMertens/flecs#855]
**Describe the bug**
Adding a component followed by clearing the entity of components causes assertion `fatal: flecs.c: 5953: assert: dst_table != NULL INTERNAL_ERROR`.

**To Reproduce**
```c++
#include "flecs.h"

#include <iostream>

struct T1 {};

int main()
{
    flecs::world ecs;
    auto e1 = ecs.entity("TestEntity1");

    ecs.defer_begin();
    e1.add<T1>();
    e1.clear();
    ecs.defer_end();
}
```

**Expected behavior**
No assertion.

**Additional context**
Ubuntu 22.04, gcc-12 for flecs, g++-12 for above.
gdb stack trace:
```gdb
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348065088) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737348065088) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737348065088, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7b63476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7b497f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555582efb in flecs_commit (world=0x555555671f30, entity=520, record=0x555555680290, dst_table=0x0, diff=0x7fffffffda50, 
    construct=true, evt_flags=0) at ../flecs/flecs.c:5953
#6  0x000055555558fdab in flecs_cmd_batch_for_entity (world=0x555555671f30, diff=0x7fffffffdb20, entity=520, cmds=0x5555557cea80, start=0)
    at ../flecs/flecs.c:9288
#7  0x00005555555901c7 in flecs_defer_end (world=0x555555671f30, stage=0x555555674c10) at ../flecs/flecs.c:9375
#8  0x000055555558ecc4 in ecs_defer_end (world=0x555555671f30) at ../flecs/flecs.c:8920
#9  0x000055555555a7c5 in flecs::world::defer_end (this=0x7fffffffdbd0) at ../co/flecs/include/flecs/private/../addons/cpp/world.hpp:277
#10 0x0000555555556b91 in main () at ./flecs_defer_end_test_2.cpp:16
```

**Comment by SanderMertens** [comment]
Fixed!
