### ISSUE TITLE
C++: Crash when using STL std::string in conjunction with a role relationship

### ISSUE THREAD

**Issue by nicokruger** [SanderMertens/flecs#875]
**Describe the bug**
When you have a std::string in a component, and then create an entity with that component and setup a role relation to another entity, it seems as if flecs is double-freeing or corrupting memory somehow. Removing the std::string from the component, or the role relationship from the entity, prevents the crash and the program exists cleanly.

**To Reproduce**
The following was done on most recent master, but I do believe 3.1.0 also had this issue:

```
#include <iostream>
#include <string>
#include <vector>
#include "flecs.h"

struct TestC {
    float a;
    float b;
    float c;
    // remove std::string in both places, and crash is avoided
    std::string str;
};
struct TestD {
    float a;
};
int main(int argc, char *argv[]) {
    flecs::world world(argc, argv);
    flecs::entity role = world.entity("MyRole");

    // change loop count to 1, and crash is avoided
    for (int i = 0; i < 100; i++) {
      auto ent1 = world.entity();
      ent1.set<TestC>({
          .a = 99,
          .b = 88,
          .c = 77,
          // remove std::string in both places, and crash is avoided
          .str = "a,b,c,d"
          });
      auto ent2 = world.entity();
      ent2.set<TestD>({
          .a = 99,
          });

      // remove role relationship, and crash is avoided
      ent1.add(ent2, role);
    }
}

```

**Expected behavior**
Cleanup should not cause invalid memory frees and references and cause the program to crash on cleanup, or when the entity is removed, for example.

**Additional context**
I was using asan as follows:

g++ -fsanitize=address -fsanitize-recover=address test.cpp flecs.

asan gives the following output when running the test program:
```
=================================================================
==11646==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x6210001592b0 in thread T0
    #0 0x7f6333d7e1fa in operator delete(void*) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:152
    #1 0x5583c351c0f3 in TestC::~TestC() (/home/nico/flecs-bug/a.out+0x650f3)
    #2 0x5583c35450c2 in void flecs::_::dtor_impl<TestC>(void*, int, ecs_type_info_t const*) (/home/nico/flecs-bug/a.out+0x8e0c2)
    #3 0x5583c354d6ad in flecs_dtor_component (/home/nico/flecs-bug/a.out+0x966ad)
    #4 0x5583c354dd1f in flecs_dtor_all_components (/home/nico/flecs-bug/a.out+0x96d1f)
    #5 0x5583c354ee10 in flecs_table_fini_data (/home/nico/flecs-bug/a.out+0x97e10)
    #6 0x5583c354feb8 in flecs_table_free (/home/nico/flecs-bug/a.out+0x98eb8)
    #7 0x5583c3550b96 in flecs_table_release (/home/nico/flecs-bug/a.out+0x99b96)
    #8 0x5583c364a0c9 in flecs_clean_tables (/home/nico/flecs-bug/a.out+0x1930c9)
    #9 0x5583c364a6d3 in flecs_fini_store (/home/nico/flecs-bug/a.out+0x1936d3)
    #10 0x5583c364e798 in ecs_fini (/home/nico/flecs-bug/a.out+0x197798)
    #11 0x5583c351b187 in flecs::world::~world() (/home/nico/flecs-bug/a.out+0x64187)
    #12 0x5583c3511f3a in main (/home/nico/flecs-bug/a.out+0x5af3a)
    #13 0x7f63337ba28f  (/usr/lib/libc.so.6+0x2328f)
    #14 0x7f63337ba349 in __libc_start_main (/usr/lib/libc.so.6+0x23349)
    #15 0x5583c35118d4 in _start ../sysdeps/x86_64/start.S:115

0x6210001592b0 is located 432 bytes inside of 4048-byte region [0x621000159100,0x62100015a0d0)
allocated by thread T0 here:
    #0 0x7f6333d7ca89 in __interceptor_malloc /usr/src/debug/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5583c3679ca8 in ecs_os_api_malloc (/home/nico/flecs-bug/a.out+0x1c2ca8)
    #2 0x5583c35979d4 in flecs_balloc_block (/home/nico/flecs-bug/a.out+0xe09d4)
    #3 0x5583c359824b in flecs_balloc (/home/nico/flecs-bug/a.out+0xe124b)
    #4 0x5583c3598303 in flecs_bcalloc (/home/nico/flecs-bug/a.out+0xe1303)
    #5 0x5583c354a050 in flecs_table_init_data (/home/nico/flecs-bug/a.out+0x93050)
    #6 0x5583c354c612 in flecs_table_init (/home/nico/flecs-bug/a.out+0x95612)
    #7 0x5583c3692111 in flecs_init_table (/home/nico/flecs-bug/a.out+0x1db111)
    #8 0x5583c36924f5 in flecs_create_table (/home/nico/flecs-bug/a.out+0x1db4f5)
    #9 0x5583c3692dbe in flecs_table_ensure (/home/nico/flecs-bug/a.out+0x1dbdbe)
    #10 0x5583c3694951 in flecs_find_table_with (/home/nico/flecs-bug/a.out+0x1dd951)
    #11 0x5583c36953bb in flecs_create_edge_for_add (/home/nico/flecs-bug/a.out+0x1de3bb)
    #12 0x5583c3695c98 in flecs_table_traverse_add (/home/nico/flecs-bug/a.out+0x1dec98)
    #13 0x5583c3561d3a in flecs_add_id (/home/nico/flecs-bug/a.out+0xaad3a)
    #14 0x5583c356d541 in ecs_add_id (/home/nico/flecs-bug/a.out+0xb6541)
    #15 0x5583c3689fcf in ecs_query_init (/home/nico/flecs-bug/a.out+0x1d2fcf)
    #16 0x5583c36208f1 in ecs_system_init (/home/nico/flecs-bug/a.out+0x1698f1)
    #17 0x5583c3632528 in FlecsRestImport (/home/nico/flecs-bug/a.out+0x17b528)
    #18 0x5583c35d5121 in ecs_import (/home/nico/flecs-bug/a.out+0x11e121)
    #19 0x5583c35d525f in ecs_import_c (/home/nico/flecs-bug/a.out+0x11e25f)
    #20 0x5583c364b8d0 in ecs_init (/home/nico/flecs-bug/a.out+0x1948d0)
    #21 0x5583c364b9c8 in ecs_init_w_args (/home/nico/flecs-bug/a.out+0x1949c8)
    #22 0x5583c351af9c in flecs::world::world(int, char**) (/home/nico/flecs-bug/a.out+0x63f9c)
    #23 0x5583c3511b2c in main (/home/nico/flecs-bug/a.out+0x5ab2c)
    #24 0x7f63337ba28f  (/usr/lib/libc.so.6+0x2328f)

SUMMARY: AddressSanitizer: bad-free /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:152 in operator delete(void*)

```

**Comment by SanderMertens** [comment]
Fixed!
